#!/usr/bin/python

from w1thermsensor import W1ThermSensor

sensor = W1ThermSensor(W1ThermSensor.THERM_SENSOR_DS18B20, "0000052fc128")
temperature_in_celsius = sensor.get_temperature()
print (temperature_in_celsius)
