#!/usr/bin/python

import argparse
from w1thermsensor import W1ThermSensor

parser = argparse.ArgumentParser()
parser.add_argument("-p","--path", required=True, help="Specify which sensor path to use")
args = parser.parse_args()

sensor = W1ThermSensor(W1ThermSensor.THERM_SENSOR_DS18B20, args.path)
temperature_in_celsius = sensor.get_temperature()
print (temperature_in_celsius)
